# This script tags the current commit, and builds a release package
name: disable-out-of-rpc-build-test
run-name: Run a build for the project with DisableOutOfProcBuild.exe for ${{ github.event_name }} triggered by ${{ github.triggering_actor }}
concurrency:
  group: test-proc

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build-with-flag-change:
    runs-on: windows-latest
    steps:
      # get the latest code from the repo
      - name: Checkout Code
        id: get-code
        uses: actions/checkout@v4

      # add msbuild and devenv to the PATH variable
      - name: Setup MSBuild
        id: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup VS Dev Environment
        id: setup-devenv
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      # - name: run the disable OutOfProc
      #   id: run-disable
      #   shell: cmd
      #   run: |
      #     DisableOutOfProcBuild.exe

      - name: build a setup project
        id: run-build-on-setup
        shell: cmd
        run: |
          devnenv .\workflow-tests.sln ^
          /Build Debug ^
          /Project workflow-tests-setup.vdproj ^
          /Log InstallerBuild.log ^
          /Out InstallerBuild.log ^
          /NoSplash

      # send build log to github output
      - name: Upload Build Log
        id: upload-build-log
        uses: actions/upload-artifact@v4
        with:
          name: build-executable-log
          path: ${{ github.workspace }}\InstallerBuild.log
          retention-days: 5

      # check for build success before continuing
      - name: Upload Check
        id: upload-check
        if: ${{ steps.run-build-on-setup.outcome != 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('user-installer build failed, no sense continuing...')

      # send build output to github output
      - name: Upload Build Artifact
        id: upload-build-artifact
        uses: actions/upload-artifact@v4
        with:
          name: workflow-tests-setup.msi
          path: ${{ github.workspace }}\workflow-tests-setup\Release\workflow-tests-setup.msi
